"""
Orders — the core transactional entity.
Includes order items (snapshots at time of order) and audit events.
"""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from shared.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin


class Order(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = "orders"

    business_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("businesses.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    customer_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("customers.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )

    # ── Order Number (human-friendly, unique per business) ───────────────
    order_number: Mapped[str] = mapped_column(
        String(32), nullable=False,
        comment="Human-friendly: BO-000123"
    )

    # ── Status ───────────────────────────────────────────────────────────
    status: Mapped[str] = mapped_column(
        String(32), default="NEW", nullable=False, index=True
    )
    payment_status: Mapped[str] = mapped_column(
        String(32), default="PENDING", nullable=False,
        comment="PENDING / PAID / CASH_ON_COLLECTION"
    )

    # ── Order Details ────────────────────────────────────────────────────
    order_mode: Mapped[str] = mapped_column(
        String(32), default="PICKUP", nullable=False,
        comment="PICKUP / DELIVERY / DINE_IN"
    )
    source: Mapped[str] = mapped_column(
        String(32), default="WHATSAPP", nullable=False,
        comment="WHATSAPP / MANUAL / ADMIN"
    )

    # ── Money (cents) ────────────────────────────────────────────────────
    subtotal_cents: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    delivery_fee_cents: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    total_cents: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    currency: Mapped[str] = mapped_column(String(3), default="ZAR", nullable=False)

    # ── Customer Info (snapshot) ─────────────────────────────────────────
    customer_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    phone_number: Mapped[str | None] = mapped_column(String(32), nullable=True)
    delivery_address: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Timestamps ───────────────────────────────────────────────────────
    estimated_ready_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    confirmed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    accepted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    ready_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── Payment ──────────────────────────────────────────────────────────
    payment_required: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False,
        comment="Snapshot of business.online_payment_required at order creation time"
    )
    payment_method: Mapped[str | None] = mapped_column(
        String(32), nullable=True,
        comment="CASH | CARD | PAY_ON_COLLECTION | DIRECT_EFT | PAYSHAP | YOCO | PAYFAST | STITCH"
    )
    payment_link_url: Mapped[str | None] = mapped_column(
        String(1024), nullable=True,
        comment="Payment link URL generated by provider (Yoco, PayFast, Stitch)"
    )
    payment_reference: Mapped[str | None] = mapped_column(
        String(255), nullable=True,
        comment="Card/EFT transaction reference, printed receipt number, etc."
    )
    paid_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
        comment="UTC timestamp when payment_status was set to PAID"
    )

    # ── Cancellation ─────────────────────────────────────────────────────
    cancelled_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    cancelled_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )

    # ── Relationships ────────────────────────────────────────────────────
    items = relationship("OrderItem", back_populates="order", lazy="selectin")
    events = relationship("OrderEvent", back_populates="order", lazy="noload")

    def __repr__(self) -> str:
        return f"<Order {self.order_number} [{self.status}]>"


class OrderItem(Base, UUIDPrimaryKeyMixin):
    __tablename__ = "order_items"

    order_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("orders.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    business_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("businesses.id", ondelete="CASCADE"),
        nullable=False,
    )
    menu_item_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True,
        comment="Nullable — menu item may have been deleted (soft delete preserves this)"
    )

    # ── Snapshot at time of order (immutable) ────────────────────────────
    name_snapshot: Mapped[str] = mapped_column(String(255), nullable=False)

    # Phase 8: full pricing breakdown — base + option deltas + add-ons = unit_price
    # Existing rows have base_price_cents = unit_price_cents and adjustments = 0.
    base_price_cents: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0,
        comment="MenuItem.price_cents at order time, before adjustments"
    )
    option_adjustment_cents: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0,
        comment="Sum of selected option price_delta_cents (may be negative)"
    )
    add_on_total_cents: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0,
        comment="Sum of add-on price_cents × quantity for this line item"
    )
    unit_price_cents: Mapped[int] = mapped_column(
        Integer, nullable=False,
        comment="base + option_adjustment + add_on_total (effective per-unit price)"
    )
    quantity: Mapped[int] = mapped_column(Integer, nullable=False)
    line_total_cents: Mapped[int] = mapped_column(Integer, nullable=False)

    # Snapshots for display and audit — these never change after order creation
    options_snapshot: Mapped[dict | None] = mapped_column(
        JSONB, nullable=True,
        comment="Raw {group_name: option_name} dict from LLM (backward compat)"
    )
    selected_options_snapshot: Mapped[list | None] = mapped_column(
        JSONB, nullable=True,
        comment="[{group_id, group_name, option_id, option_name, price_delta_cents}]"
    )
    add_ons_snapshot: Mapped[list | None] = mapped_column(
        JSONB, nullable=True,
        comment="[{add_on_id, name, price_cents, quantity}]"
    )
    special_instructions: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Relationships ────────────────────────────────────────────────────
    order = relationship("Order", back_populates="items")


class OrderEvent(Base, UUIDPrimaryKeyMixin):
    """Audit trail for order status changes."""
    __tablename__ = "order_events"

    order_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("orders.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    business_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("businesses.id", ondelete="CASCADE"),
        nullable=False,
    )
    old_status: Mapped[str | None] = mapped_column(String(32), nullable=True)
    new_status: Mapped[str] = mapped_column(String(32), nullable=False)
    changed_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=lambda: __import__("datetime").datetime.now(__import__("datetime").timezone.utc),
    )

    # ── Relationships ────────────────────────────────────────────────────
    order = relationship("Order", back_populates="events")
